/**
 * Travelport — the third inventory source, named in docs/02 as the alternative
 * GDS once Amadeus Self-Service was decommissioned (17 Jul 2026).
 *
 * We have no credentials, so this returns a deterministic synthetic book —
 * generated by server/suppliers/mockFlights.ts from real route geometry and
 * a real-carrier reference table (server/mockData/airlines.json), not a flat
 * random band — and flags every offer `live: false`. It exists for two
 * honest reasons: to prove the supplier abstraction is not shaped around any
 * one vendor, and to give the scarcity input in lib/thresholds.ts something
 * to count on routes where the two live sandboxes return nothing. It must
 * never be presented as real inventory.
 */

import { generateFlightOffers } from './mockFlights';
import type { RevalidationResult, Supplier, SupplierStatus } from './types';

export const travelport: Supplier = {
  id: 'travelport',

  async search(params) {
    if (!process.env.TRAVELPORT_API_KEY) {
      return { offers: generateFlightOffers(params), status: 'ok' as SupplierStatus };
    }
    // Real integration lands here once access exists; the shape above is the contract.
    return { offers: generateFlightOffers(params), status: 'ok' };
  },

  async revalidate(): Promise<RevalidationResult> {
    // Synthetic inventory cannot be re-checked against anything real.
    return { state: 'unknown' };
  },
};
